### ISSUE TITLE
Feedback from Tableau - consider using version min/max

### ISSUE THREAD

**Issue by clach04** [ActianCorp/actian_tableau_connector#8]
From https://github.com/tableau/connector-plugin-sdk/blob/master/samples/components/resolvers/full_example.tdr#L89

See line that I've marked with `XXXX`:

    <driver-resolver>
    
    
    <driver-match platform='win'>
      
      <driver-name type="exact">My Driver is named exactly this</driver-name>
    XXXX  <driver-version max="5.2" min="5.1"/>
    </driver-match>
    <driver-match>
      <driver-name type='regex'>My Dri.*</driver-name>
      <driver-version max="5.2.19" min="5.1"/>
      <incompatible-driver-version exact="5.2.9"/>
      
    </driver-match>

    </driver-resolver>

**Comment by clach04** [comment]
@BruceLunsford is there a minimum Client driver version for Avalanche/Vector that you'd recommend the Tableau connector should enforce?

**Comment by BruceLunsford** [comment]
I don't recommend setting a minimum ODBC driver version because they vary by Ingres/Vector release.  So an Ingres 11.1 Windows client will be 3.50.1110.xxx whereas the recent Vector-based client runtime is 3.50.1120.yyy.  xxx/yyy are patch versions and can vary across releases as to what bug fixes they include.  Most of the recent bug fixes have been very specific and not likely to affect most users.  Unless you know of a specific bug fix in the ODBC driver that was preventing Tableau from working, the last major bug fix (in my opinion) that would be "worthy" of being considered a minimum, was bug 135215, which could either skip rows or issue an error after several iterations of SQLFetchScroll() or SQLExtendedFetch(), which are fairly common functions when retrieving lots of data.

**Comment by clach04** [comment]
Thanks @BruceLunsford, that's where my head was at too. Closing.
